name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up environment variables
        run: |
          echo "APP_NAME=conditional-launcher" >> $GITHUB_ENV
          echo "ASSET_NAME=conditional-launcher-linux-x86_64" >> $GITHUB_ENV

      - name: Build binary
        run: cargo build --release --locked --target x86_64-unknown-linux-gnu

      - name: Prepare asset
        run: mv target/x86_64-unknown-linux-gnu/release/${{ env.APP_NAME }} ${{ env.ASSET_NAME }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ASSET_NAME }}
